### ISSUE TITLE
Faire des screenshots des alumnis

### ISSUE THREAD

**Issue by sebousan** [noesya/osuny-www#7]
https://extranet.mmibordeaux.com/

**Comment by Olivia206** [comment]
Accueil :
![alumni_accueil](https://user-images.githubusercontent.com/91660674/172836311-bfe450be-e78a-47dc-9f85-b549122e4d7c.png)

Liste des alumni :
![alumni_liste](https://user-images.githubusercontent.com/91660674/172836315-e21d5cf1-857e-427b-991e-3832262c80c5.png)

Profil alumni : 
![alumni_profil](https://user-images.githubusercontent.com/91660674/172836299-a2578111-8120-44f2-9135-78c861d88b93.png)

Liste promotions :
![alumni_promotions](https://user-images.githubusercontent.com/91660674/172836304-337c775b-720a-42a7-bf85-acdd5471f1db.png)

Une promo :
![alumni_1promo](https://user-images.githubusercontent.com/91660674/172836309-8a3bd133-91f8-4493-a394-951e56ad6d9b.png)

Liste des années :
![alumni_années](https://user-images.githubusercontent.com/91660674/172836313-3bd4db2f-6f43-47f5-91c1-9bc5e164f835.png)

Liste des organisations: 
![alumni_organisations](https://user-images.githubusercontent.com/91660674/172836320-6e6fce78-5e13-485c-b9f6-c955e9715f90.png)

Une organisation :
![alumni_1orga](https://user-images.githubusercontent.com/91660674/172836306-10fb413e-89f4-491d-8b56-06752ce26c08.png)

Je raccourcis les screens les plus longs ?

**Comment by arnaudlevy** [comment]
@Olivia206 https://www.osuny.org/fonctionnalites/communication/extranets/
